// Reviewed final-schema inventory. New DDL must explicitly update this contract.
export const backupTableKeys: Readonly<Record<string, readonly string[]>> = {
  agent_identity_cache: ["tenant_id", "principal_id", "record_id"],
  agent_people_cache: ["tenant_id", "principal_id", "object_id"],
  agent_usage_associations: ["tenant_id", "report_set_id", "report_agent_id"],
  agent_usage_state: ["tenant_id"],
  app_activity_rows: ["generation_id", "identity"],
  app_schema: ["singleton"],
  audit_events: ["id"],
  capability_configuration: ["tenant_id", "capability_id"],
  capability_evidence: ["tenant_id", "principal_id", "authorization_principal_id", "capability_id", "resource_audience", "environment_id", "token_mode", "permission_revision", "contract_revision", "configuration_revision"],
  copilot_quarantine_attempts: ["id"],
  copilot_quarantine_audit: ["id"],
  copilot_quarantine_canary_approvals: ["id"],
  copilot_quarantine_job_items: ["id"],
  copilot_quarantine_jobs: ["id"],
  copilot_quarantine_qualifications: ["id"],
  copilot_quarantine_status_observations: ["id"],
  data_export_chunks: ["export_id", "ordinal"],
  data_export_items: ["export_id", "ordinal"],
  data_exports: ["id"],
  data_generation_batches: ["generation_id", "ordinal"],
  data_generation_charges: ["scope_id"],
  data_generation_heads: ["scope_id"],
  data_generation_pages: ["generation_id", "ordinal"],
  data_generation_pins: ["selection_id", "ordinal"],
  data_generations: ["id"],
  data_lifecycle_progress: ["worker"],
  inventory_collection_progress: ["scope_id"],
  data_principal_epochs: ["tenant_id", "principal_id"],
  data_read_selections: ["id"],
  data_scope_epochs: ["id"],
  data_sync_run_sources: ["run_id", "source_id"],
  data_sync_runs: ["id"],
  data_sync_source_jobs: ["run_id", "source_id", "attempt"],
  data_sync_success_markers: ["tenant_id", "principal_id", "source_id"],
  defender_hunting_jobs: ["id"],
  defender_hunting_qualification_evidence: ["id"],
  defender_hunting_retained_scopes: ["id"],
  defender_hunting_rows: ["snapshot_id", "row_ordinal"],
  defender_hunting_snapshots: ["id"],
  directory_service_plan_rows: ["generation_id", "identity"],
  directory_user_rows: ["generation_id", "identity"],
  inventory_attempts: ["generation_id"],
  inventory_candidate_edges: ["worker_id", "left_scope", "left_id", "right_scope", "right_id"],
  inventory_canonical_ids: ["id"],
  inventory_changes: ["scope_id", "revision", "identity"],
  inventory_compaction_refs: ["generation_id", "identity"],
  inventory_control_pending: ["tenant_id", "principal_id", "target_id"],
  inventory_exact_heads: ["scope_id", "observation_epoch", "identity"],
  inventory_facts: ["generation_id", "identity", "ordinal"],
  inventory_frontier: ["worker_id", "source_scope_id", "identity"],
  inventory_keys: ["generation_id", "identity"],
  inventory_memberships: ["baseline_id", "identity", "valid_from_revision"],
  inventory_mutation_stages: ["id"],
  inventory_mutation_targets: ["stage_id", "target_id"],
  inventory_native_control_pending: ["scope_id", "identity"],
  inventory_pages: ["generation_id", "ordinal"],
  inventory_people_revisions: ["tenant_id", "principal_id"],
  inventory_read_contexts: ["selection_id"],
  inventory_reconciliation: ["scope_id"],
  inventory_reconciliation_keys: ["scope_id", "sequence", "source_scope_id", "identity"],
  inventory_refresh_targets: ["job_id", "ordinal"],
  inventory_revisions: ["scope_id", "revision"],
  inventory_roots: ["baseline_id"],
  inventory_worker_pins: ["worker_id", "scope_id"],
  job_attempts: ["id"],
  job_items: ["id"],
  jobs: ["id"],
  official_usage_artifacts: ["id"],
  official_usage_audit: ["id"],
  official_usage_bundle_receipts: ["tenant_id", "bundle_id"],
  official_usage_confirmations: ["id"],
  official_usage_history_memberships: ["tenant_id", "set_id", "valid_from_revision"],
  official_usage_history_state: ["tenant_id"],
  official_usage_ingestion_rows: ["ingestion_id", "ordinal"],
  official_usage_ingestions: ["id"],
  official_usage_membership_counts: ["version_id"],
  official_usage_read_contexts: ["selection_id"],
  official_usage_row_facts: ["tenant_id", "kind", "payload_hash"],
  official_usage_set_versions: ["set_id", "kind"],
  official_usage_sets: ["id"],
  official_usage_staged_rows: ["staging_id", "ordinal"],
  official_usage_staging: ["id"],
  official_usage_state: ["tenant_id"],
  official_usage_version_rows: ["version_id", "ordinal"],
  official_usage_versions: ["id"],
  operational_state: ["singleton"],
  package_inventory_resources: ["snapshot_id", "native_id"],
  package_inventory_snapshots: ["id"],
  package_mutation_qualifications: ["id"],
  package_record_rows: ["generation_id", "identity"],
  package_refresh_jobs: ["id"],
  power_platform_record_rows: ["generation_id", "identity"],
  power_platform_refresh_jobs: ["id"],
  purview_audit_jobs: ["id"],
  purview_audit_qualifications: ["id"],
  purview_audit_records: ["job_id", "wrapper_id"],
  sessions: ["sid"],
  source_identifiers: ["id"],
  unified_agent_memberships: ["generation_id", "identity", "source_scope_id", "source_identity"],
  unified_agent_rows: ["generation_id", "identity"],
  user_source_attempts: ["generation_id"],
  user_source_identity_inputs: ["generation_id", "identity"],
  user_source_queries: ["generation_id", "query_key"],
  user_source_query_members: ["generation_id", "query_key", "identity"],
  user_source_read_contexts: ["selection_id"],
  user_source_skus: ["generation_id", "sku_id"],
};
export const fingerprintAlgorithm = "sha256-pg-row-json-pkey-utf8-v1";
