using './main.bicep'

param environmentName = 'dev'
param location = 'eastus2'
param staticWebAppLocation = 'westeurope'
param namePrefix = 'agent-control'
param appRegistrationClientId = '<existing-entra-app-client-id>'
param keyVaultName = '<existing-key-vault-name>'
param keyVaultNetworkAccess = 'Public'
param virtualNetworkAddressPrefix = '10.42.0.0/24'
param appServiceIntegrationSubnetPrefix = '10.42.0.0/26'
param privateEndpointSubnetPrefix = '10.42.0.64/27'
