import type {
  WorkbenchActionDefinition,
  WorkbenchMetadata,
  WorkbenchViewDefinition,
} from "../types/workbench.js";

export const workbenchViews: WorkbenchViewDefinition[] = [
  { id: "agents", label: "Agents", path: "/agents", roles: ["AgentControl.Viewer"], source: "Graph packages and exact control targets" },
  { id: "power-platform", label: "Power Platform", path: "/power-platform", roles: ["AgentControl.Viewer"], source: "Power Platform Resource Query" },
  { id: "users", label: "Users", path: "/users", roles: ["AgentControl.Viewer"], source: "Official usage Users and Users & agents exports" },
  { id: "official-usage", label: "Official usage", path: "/official-usage", roles: ["AgentControl.Viewer"], source: "Microsoft 365 admin-center three-file exports" },
  { id: "audit", label: "Audit", path: "/audit", roles: ["AgentControl.Viewer"], source: "Local administrative audit and Microsoft Purview Audit Search" },
  { id: "security", label: "Security", path: "/security", roles: ["AgentControl.Viewer"], source: "Defender fixed-template hunting" },
  { id: "permissions", label: "Permissions", path: "/permissions", roles: ["AgentControl.Viewer"], source: "Agent Control capability registry" },
  { id: "jobs", label: "Jobs", path: "/jobs", roles: ["AgentControl.Viewer"], source: "Authorized user-requested work" },
];

export const workbenchActions: WorkbenchActionDefinition[] = [
  { id: "audit.export", label: "Export exact administrative audit page", roles: ["AgentControl.Viewer"], capabilityId: null,
    nativeTarget: "none", preview: "none", confirmation: "explicit", recovery: "none", method: "POST", route: "/api/audit/events/export.csv", source: "local_audit" },
  { id: "packages.inspect", label: "Inspect saved package", roles: ["AgentControl.Viewer"], capabilityId: null, nativeTarget: "graph_package_id", preview: "none", confirmation: "none", recovery: "none", method: "GET", route: "/api/agents/:id", source: "graph_packages" },
  { id: "packages.refresh", label: "Refresh package inventory", roles: ["AgentControl.Viewer"], capabilityId: "graph.package.read.delegated", nativeTarget: "none", preview: "none", confirmation: "explicit", recovery: "reauthorize", method: "POST", route: "/api/agents/refresh-jobs", source: "graph_packages" },
  { id: "packages.refresh.exact", label: "Refresh exact package", roles: ["AgentControl.Viewer"], capabilityId: "graph.package.read.delegated", nativeTarget: "graph_package_id", preview: "none", confirmation: "explicit", recovery: "reauthorize", method: "POST", route: "/api/agents/:id/refresh-jobs", source: "graph_packages" },
  { id: "packages.refresh.resume", label: "Resume package inventory refresh", roles: ["AgentControl.Viewer"], capabilityId: "graph.package.read.delegated", nativeTarget: "provider_job_id", preview: "none", confirmation: "explicit", recovery: "resume_unsent", method: "POST", route: "/api/agents/refresh-jobs/:id/resume", source: "graph_packages" },
  { id: "packages.refresh.exact.resume", label: "Resume exact package refresh", roles: ["AgentControl.Viewer"], capabilityId: "graph.package.read.delegated", nativeTarget: "provider_job_id", preview: "none", confirmation: "explicit", recovery: "resume_unsent", method: "POST", route: "/api/agents/refresh-jobs/:id/resume", source: "graph_packages" },
  { id: "packages.refresh.cancel", label: "Cancel package inventory refresh", roles: ["AgentControl.Viewer"], capabilityId: null, nativeTarget: "provider_job_id", preview: "none", confirmation: "explicit", recovery: "cancel_unsent", method: "POST", route: "/api/agents/refresh-jobs/:id/cancel", source: "graph_packages" },
  { id: "packages.export", label: "Export package inventory", roles: ["AgentControl.Viewer"], capabilityId: null, nativeTarget: "graph_package_id", preview: "none", confirmation: "explicit", recovery: "none", method: "POST", route: "/api/agents/export.csv", source: "graph_packages" },
  { id: "packages.block", label: "Block package", roles: ["AgentControl.Admin"], capabilityId: "graph.package.block.manage", nativeTarget: "graph_package_id", preview: "required", confirmation: "risk_and_exact_targets", recovery: "reconcile_get_only", method: "POST", route: "/api/agents/:id/block", source: "graph_packages" },
  { id: "packages.unblock", label: "Unblock package", roles: ["AgentControl.Admin"], capabilityId: "graph.package.block.manage", nativeTarget: "graph_package_id", preview: "required", confirmation: "risk_and_exact_targets", recovery: "reconcile_get_only", method: "POST", route: "/api/agents/:id/unblock", source: "graph_packages" },
  { id: "packages.access", label: "Replace package access", roles: ["AgentControl.Admin"], capabilityId: "graph.package.access.manage", nativeTarget: "graph_package_id", preview: "required", confirmation: "risk_and_exact_targets", recovery: "reconcile_get_only", method: "PATCH", route: "/api/agents/:id/access", source: "graph_packages" },
  { id: "packages.resume", label: "Resume unsent package controls", roles: ["AgentControl.Admin"], capabilityId: null, nativeTarget: "provider_job_id", preview: "none", confirmation: "explicit", recovery: "resume_unsent", method: "POST", route: "/api/agents/bulk-jobs/:id/resume", source: "graph_packages" },
  { id: "packages.cancel", label: "Cancel unsent package controls", roles: ["AgentControl.Admin"], capabilityId: null, nativeTarget: "provider_job_id", preview: "none", confirmation: "explicit", recovery: "cancel_unsent", method: "POST", route: "/api/agents/bulk-jobs/:id/cancel", source: "graph_packages" },
  { id: "packages.reconcile", label: "Reconcile uncertain package control", roles: ["AgentControl.Admin"], capabilityId: null, nativeTarget: "provider_job_id", preview: "none", confirmation: "explicit", recovery: "reconcile_get_only", method: "POST", route: "/api/agents/bulk-jobs/:id/reconcile", source: "graph_packages" },
  { id: "power-platform.refresh", label: "Refresh Power Platform inventory", roles: ["AgentControl.Viewer"], capabilityId: "powerPlatform.inventory.read", nativeTarget: "none", preview: "none", confirmation: "explicit", recovery: "reauthorize", method: "POST", route: "/api/inventory/refresh-jobs", source: "power_platform" },
  { id: "power-platform.resume", label: "Resume Power Platform refresh", roles: ["AgentControl.Viewer"], capabilityId: "powerPlatform.inventory.read", nativeTarget: "provider_job_id", preview: "none", confirmation: "explicit", recovery: "resume_unsent", method: "POST", route: "/api/inventory/refresh-jobs/:id/resume", source: "power_platform" },
  { id: "power-platform.cancel", label: "Cancel Power Platform refresh", roles: ["AgentControl.Viewer"], capabilityId: null, nativeTarget: "provider_job_id", preview: "none", confirmation: "explicit", recovery: "cancel_unsent", method: "POST", route: "/api/inventory/refresh-jobs/:id/cancel", source: "power_platform" },
  { id: "power-platform.export", label: "Export Power Platform inventory", roles: ["AgentControl.Viewer"], capabilityId: null, nativeTarget: "power_platform_resource_id", preview: "none", confirmation: "none", recovery: "none", method: "GET", route: "/api/inventory/export.csv", source: "power_platform" },
  { id: "quarantine.change", label: "Change Copilot Studio quarantine", roles: ["AgentControl.Admin"], capabilityId: "powerPlatform.quarantine.manage", nativeTarget: "copilot_environment_bot", preview: "required", confirmation: "risk_and_exact_targets", recovery: "reconcile_get_only", method: "POST", route: "/api/quarantine/jobs", source: "power_platform" },
  { id: "quarantine.resume", label: "Resume unsent quarantine controls", roles: ["AgentControl.Admin"], capabilityId: "powerPlatform.quarantine.manage", nativeTarget: "provider_job_id", preview: "none", confirmation: "explicit", recovery: "resume_unsent", method: "POST", route: "/api/quarantine/jobs/:id/resume", source: "power_platform" },
  { id: "quarantine.cancel", label: "Cancel unsent quarantine controls", roles: ["AgentControl.Admin"], capabilityId: null, nativeTarget: "provider_job_id", preview: "none", confirmation: "explicit", recovery: "cancel_unsent", method: "POST", route: "/api/quarantine/jobs/:id/cancel", source: "power_platform" },
  { id: "quarantine.reconcile", label: "Reconcile uncertain quarantine result", roles: ["AgentControl.Admin"], capabilityId: "powerPlatform.quarantine.manage", nativeTarget: "provider_job_id", preview: "none", confirmation: "explicit", recovery: "reconcile_get_only", method: "POST", route: "/api/quarantine/jobs/:id/reconcile", source: "power_platform" },
  { id: "usage.import", label: "Import official usage", roles: ["AgentControl.Admin"], capabilityId: "reports.official.import", nativeTarget: "official_usage_set", preview: "required", confirmation: "explicit", recovery: "none", method: "POST", route: "/api/official-usage/bundles/:id/accept", source: "official_usage" },
  { id: "usage.staging.cancel", label: "Discard actor-owned staging", roles: ["AgentControl.Admin"], capabilityId: null, nativeTarget: "official_usage_set", preview: "none", confirmation: "explicit", recovery: "cancel_unsent", method: "DELETE", route: "/api/official-usage/staging/:id", source: "official_usage" },
  { id: "usage.export.aggregate", label: "Export aggregate official usage", roles: ["AgentControl.Viewer"], capabilityId: null, nativeTarget: "official_usage_set", preview: "none", confirmation: "none", recovery: "none", method: "GET", route: "/api/official-usage/aggregate.csv", source: "official_usage" },
  { id: "usage.export.users", label: "Export user official usage", roles: ["AgentControl.Viewer"], capabilityId: null, nativeTarget: "official_usage_set", preview: "none", confirmation: "none", recovery: "none", method: "GET", route: "/api/official-usage/users.csv", source: "official_usage" },
  { id: "purview.search", label: "Run Purview Audit Search", roles: ["AgentControl.Viewer"], capabilityId: "purview.audit.search.delegated", nativeTarget: "purview_query_window", preview: "required", confirmation: "explicit", recovery: "reauthorize", method: "POST", route: "/api/audit-search/jobs", source: "purview" },
  { id: "purview.resume", label: "Resume Purview search", roles: ["AgentControl.Viewer"], capabilityId: "purview.audit.search.delegated", nativeTarget: "provider_job_id", preview: "none", confirmation: "explicit", recovery: "resume_unsent", method: "POST", route: "/api/audit-search/jobs/:id/resume", source: "purview" },
  { id: "purview.cancel", label: "Cancel Purview search", roles: ["AgentControl.Viewer"], capabilityId: null, nativeTarget: "provider_job_id", preview: "none", confirmation: "explicit", recovery: "cancel_unsent", method: "POST", route: "/api/audit-search/jobs/:id/cancel", source: "purview" },
  { id: "purview.export", label: "Export Purview results", roles: ["AgentControl.Viewer"], capabilityId: null, nativeTarget: "provider_job_id", preview: "none", confirmation: "none", recovery: "none", method: "GET", route: "/api/audit-search/jobs/:id/export.csv", source: "purview" },
  { id: "defender.search", label: "Run fixed Defender investigation", roles: ["AgentControl.Viewer"], capabilityId: "defender.hunting.delegated", nativeTarget: "defender_fixed_template_window", preview: "required", confirmation: "explicit", recovery: "reauthorize", method: "POST", route: "/api/hunting/jobs", source: "defender" },
  { id: "defender.resume", label: "Resume Defender investigation", roles: ["AgentControl.Viewer"], capabilityId: "defender.hunting.delegated", nativeTarget: "provider_job_id", preview: "none", confirmation: "explicit", recovery: "resume_unsent", method: "POST", route: "/api/hunting/jobs/:id/resume", source: "defender" },
  { id: "defender.cancel", label: "Cancel Defender investigation", roles: ["AgentControl.Viewer"], capabilityId: null, nativeTarget: "provider_job_id", preview: "none", confirmation: "explicit", recovery: "cancel_unsent", method: "POST", route: "/api/hunting/jobs/:id/cancel", source: "defender" },
  { id: "defender.export", label: "Export allowlisted Defender results", roles: ["AgentControl.Viewer"], capabilityId: null, nativeTarget: "provider_job_id", preview: "none", confirmation: "none", recovery: "none", method: "GET", route: "/api/hunting/jobs/:id/export.csv", source: "defender" },
];

export function getWorkbenchMetadata(): WorkbenchMetadata {
  return {
    views: workbenchViews.map(view => ({ ...view, roles: [...view.roles] })),
    actions: workbenchActions.map(action => ({ ...action, roles: [...action.roles] })),
  };
}
